<?php

//------------------------------------------------------------------------------------------
// Perform initial set up tasks

//ensure that the correct timezone is set
if( function_exists( 'data_default_timezone_set' ) )
{
    date_default_timezone_set( 'America/New_York' );
}

// include the QuickBooks library
ini_set( 'include_path', ini_get( 'include_path' ). PATH_SEPARATOR . '/var/www/QBWC/QuickBooks/' );

require_once 'QuickBooks.php';

error_reporting( E_ALL | E_STRICT );
$log_level = QUICKBOOKS_LOG_DEVELOP;

//------------------------------------------------------------------------------------------

// Username and password used to connect to this service through the QBWC
// this might want to be moved later, but for now should be ok sitting here
$user = "quickbooks";
$pass = "password";

// handler mapping
// room for additional mappings if future projects arise. for now just need timetracking
$map = array( QUICKBOOKS_ADD_TIMETRACKING => array( '_quickbooks_timetracking_add_request', '_quickbooks_timetracking_add_response' ) );

$errmap = array( );
$hooks = array( );

// connection to the Sarariman database
$dsn = 'mysql://root:diggy@localhost/sarariman';

//------------------------------------------------------------------------------------------

if( !QuickBooks_Utilities::initialized( $dsn ) )
{
    // Create the neccesary database schema for queueing requests
    QuickBooks_Utilities::initialize( $dsn );

    // Create a username and password which is used by the QBWC to authenticate
    QuickBooks_Utilities::createUser( $dsn, $user, $pass );
}

//------------------------------------------------------------------------------------------

$Server  = new QuickBooks_Server( $dsn, $map, $errmap, $hooks, $log_level );
$response = $Server->handle( true, true );

//------------------------------------------------------------------------------------------
// Create the handler methods for the timetracking request/response

function _quickbooks_timetracking_add_request( $requestID, $user, $action, $ID, $extra, &$err, $last_action_time, $last_actionident_time, $version, $locale )
{
    // The qbXML is already properly generated by the sarariman web-service (sarariman/src/java/com/dignitastechnologies/sarariman/qb/qbXMLWriter.java).
    // It is saved at sarariman_qb.txt (/var/www/QBWC/res/sarariman_qb.txt), so simply a matter of reading it in.

    $file = "res/sarariman_qb.txt";
    $fh   = fopen( $file, 'r') or die( "failed to open $file" );
    $xml  = fread( $fh, filesize( $file ) );

    fclose( $fh );

    //lwrite( "TimeTrackingAdd request processed" );

    return $xml;
}

function _quickbooks_timetracking_add_response( $requestID, $user, $action, $ID, $extra, &$err, $last_action_time, $last_actionident_time, $xml, $idents )
{
    // Log the response to /var/www/QBWC/logs/QBWC_Response.txt

    $file = "log/QBWC_Response.txt";
    $fh   = fopen( $file, 'a' ) or die ( "failed to open $file" );

    $str = "\nNEW ENTRY\n#################### $last_action_time\n\n";

    fwrite( $fh, $str );
    fwrite( $fh, $xml );

    fclose( $fh );

//    lwrite( "TimeTrackingAdd response processed" );

    return;
}

?>
